# Generated by Django 5.0.3 on 2024-03-19 18:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Volunteer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, verbose_name='user name')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('age', models.CharField(max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10)),
                ('identity_id', models.CharField(default='456', max_length=11)),
                ('user', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'volunteer',
                'verbose_name_plural': 'volunteers',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='LonelyHuman',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=30, verbose_name='name')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('age', models.CharField(choices=[('under18', 'Under 18'), ('18to25', '18 - 25'), ('26to35', '26 - 35'), ('36to50', '36 - 50'), ('over50', 'Over 50')], max_length=10)),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('secret', 'I do not want to say')], max_length=10)),
                ('description', models.CharField(max_length=1000)),
                ('communication_style', models.CharField(choices=[('email', 'By E-Mail'), ('phone', 'By Phone'), ('live', 'Live meet')], max_length=10)),
                ('required_age_from', models.IntegerField()),
                ('required_age_to', models.IntegerField()),
                ('required_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Not important')], max_length=10)),
                ('volunteer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lonelyhuman', to='registration.volunteer', verbose_name='volunteer')),
            ],
            options={
                'verbose_name': 'lonelyhuman',
                'verbose_name_plural': 'lonelyhumans',
                'ordering': ['name'],
            },
        ),
    ]
