# Generated by Django 5.0.3 on 2024-03-24 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lonelyhumanprofile',
            options={'ordering': ['id'], 'verbose_name': 'lonelyhumanprofile', 'verbose_name_plural': 'lonelyhumanprofiles'},
        ),
        migrations.AlterModelOptions(
            name='volunteerprofile',
            options={'ordering': ['id'], 'verbose_name': 'volunteerprofile', 'verbose_name_plural': 'volunteerprofiles'},
        ),
        migrations.RemoveField(
            model_name='lonelyhumanprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='lonelyhumanprofile',
            name='username',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='email',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='identity_id',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='username',
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='personal_no',
            field=models.CharField(default=0, max_length=15, verbose_name='personal_no'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='age',
            field=models.CharField(choices=[('under18', 'Under 18'), ('18to25', '18 - 25'), ('26to35', '26 - 35'), ('36to50', '36 - 50'), ('over50', 'Over 50')], max_length=7, verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='communication_style',
            field=models.CharField(choices=[('E', 'By E-Mail'), ('P', 'By Phone'), ('L', 'Live meet')], max_length=1, verbose_name='communication style'),
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('S', 'I do not want to say')], max_length=1, verbose_name='gender'),
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='required_age_from',
            field=models.IntegerField(verbose_name='required age from'),
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='required_age_to',
            field=models.IntegerField(verbose_name='required age to'),
        ),
        migrations.AlterField(
            model_name='lonelyhumanprofile',
            name='required_gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female'), ('B', "Doesn't matter")], max_length=1, verbose_name='required gender'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='age',
            field=models.IntegerField(verbose_name='age'),
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1, verbose_name='gender'),
        ),
    ]
