# Generated by Django 5.0.3 on 2024-03-21 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lonelyhuman',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username'),
        ),
        migrations.AlterField(
            model_name='volunteer',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='user name'),
        ),
    ]
