# Generated by Django 5.0.3 on 2024-03-22 07:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_lonelyhuman_username_alter_volunteer_username'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='volunteer',
            name='lonelyhuman',
        ),
        migrations.CreateModel(
            name='LonelyHumanProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, unique=True, verbose_name='username')),
                ('name', models.CharField(max_length=30, verbose_name='name')),
                ('email', models.EmailField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('age', models.CharField(choices=[('under18', 'Under 18'), ('18to25', '18 - 25'), ('26to35', '26 - 35'), ('36to50', '36 - 50'), ('over50', 'Over 50')], max_length=10, verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('secret', 'I do not want to say')], max_length=10, verbose_name='gender')),
                ('description', models.TextField(max_length=1000, verbose_name='description')),
                ('communication_style', models.CharField(choices=[('email', 'By E-Mail'), ('phone', 'By Phone'), ('live', 'Live meet')], max_length=10, verbose_name='communication Style')),
                ('required_age_from', models.IntegerField(verbose_name='required Age From')),
                ('required_age_to', models.IntegerField(verbose_name='required Age To')),
                ('required_gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('both', 'Not important')], max_length=10, verbose_name='required Gender')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'lonelyhumanprofile',
                'verbose_name_plural': 'lonelyhumanprofiles',
                'ordering': ['username'],
            },
        ),
        migrations.CreateModel(
            name='VolunteerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(db_index=True, max_length=20, verbose_name='user name')),
                ('first_name', models.CharField(max_length=30, verbose_name='first name')),
                ('last_name', models.CharField(max_length=30, verbose_name='last name')),
                ('email', models.CharField(blank=True, max_length=50, null=True, verbose_name='email')),
                ('phone', models.CharField(blank=True, max_length=50, null=True, verbose_name='phone')),
                ('age', models.CharField(max_length=10, verbose_name='Age')),
                ('gender', models.CharField(choices=[('male', 'Male'), ('female', 'Female')], max_length=10, verbose_name='gender')),
                ('identity_id', models.CharField(default='456', max_length=11, verbose_name='identity_id')),
                ('lonelyhuman', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lonelyhuman', to='registration.lonelyhumanprofile', verbose_name='volunteer')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='user')),
            ],
            options={
                'verbose_name': 'volunteerprofile',
                'verbose_name_plural': 'volunteerprofiles',
                'ordering': ['username'],
            },
        ),
        migrations.DeleteModel(
            name='LonelyHuman',
        ),
        migrations.DeleteModel(
            name='Volunteer',
        ),
    ]
