# Generated by Django 5.0.3 on 2024-03-25 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0002_alter_lonelyhumanprofile_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lonelyhumanprofile',
            name='role',
            field=models.CharField(choices=[('LONELYHUMAN', 'lonely human'), ('VOLUNTEER', 'Volunteer')], default='LONELYHUMAN', max_length=20),
        ),
        migrations.AddField(
            model_name='volunteerprofile',
            name='role',
            field=models.CharField(choices=[('LONELYHUMAN', 'lonely human'), ('VOLUNTEER', 'Volunteer')], default='VOLUNTEER', max_length=20),
        ),
    ]
