# Generated by Django 5.0.3 on 2024-03-22 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0003_remove_volunteer_lonelyhuman_lonelyhumanprofile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='volunteerprofile',
            name='identity_id',
            field=models.CharField(max_length=15, verbose_name='identity_id'),
        ),
    ]
