# Generated by Django 5.0.3 on 2024-03-22 08:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_volunteerprofile_identity_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lonelyhumanprofile',
            name='name',
        ),
        migrations.AlterField(
            model_name='volunteerprofile',
            name='username',
            field=models.CharField(db_index=True, max_length=20, unique=True, verbose_name='user name'),
        ),
    ]
