# Generated by Django 5.0.3 on 2024-03-25 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0004_alter_lonelyhumanprofile_role_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lonelyhumanprofile',
            name='role',
        ),
        migrations.RemoveField(
            model_name='volunteerprofile',
            name='role',
        ),
    ]
